Nodify, bundle and deprecate old files
Palindrom/JSON-Patch-Queue pull request #4
Opened 2017-03-03 13:03 UTC by alshakero

Related to https://github.com/Palindrom/JSON-Patch-OT/issues/5.

This is 100% backward compatible. Yet 100% Node and future Palindrom compatible.

Tested with Browser `<script />`, Node CommonJS, Babel ES6 imports and TS imports. All Jasmine tests pass on Node and browser.

With great Tyings files, thanks to @tomalec awesome JSDoc.

Usage examples (tested each):
```html
<script src='dist/json-patch-queue-synchronous.min.js'></script>
```
or
```html
<script src='dist/json-patch-queue.min.js'></script>
```

in Node's CommonJS
```js
var JSONPatchQueue = require('json-patch-queue').JSONPatchQueue;
```
in Node's TS and ES6
```js
import { JSONPatchQueue } from 'json-patch-queue';
```
or
```js
import { JSONPatchQueueSynchronous } from 'json-patch-queue';
```

2017-03-06 09:31 UTC, alshakero commented
@tomalec ready for review.

2017-03-08 13:41 UTC, tomalec requested changes
For me it looks kinde hacky that just ot be able to do https://github.com/Palindrom/JSON-Patch-Queue/pull/4/files#diff-eb50505eb60eb228148efeebce771b5f

Write 
```js
module.exports = JSONPatchQueue;
module.exports.default = JSONPatchQueue; 
```
instead of 
```js
if (typeof module !== "undefined") {
    module.exports = JSONPatchQueue;
}
```

We need to load 75lines = 28% code more in the browser.
https://github.com/Palindrom/JSON-Patch-Queue/pull/4/files#diff-8abfd87d68e18e03b76cb3f3591fc129

2017-03-08 13:41 UTC, tomalec commented on gruntfile.js
> -module.exports = function(grunt) {
Don't we need bump task any longer?

2017-03-08 13:47 UTC, tomalec commented
I'd rather expect it to be:

1. Plain source file without any webpack related stuff, that could be easily maintained and loaded as good old, non-bundled `<script src='src/json-patch-queue.js'></script>`
2. module ready version that works with node, commonjs, babel, ts, liek  `<script src='dist/json-patch-queue.js'></script>`, as this is the version which requires just 4 lines more, comparing to source
3. Bundled version with all deps (not applicable here, as this one has none) ready for browsers

2017-03-09 12:43 UTC, alshakero commented on gruntfile.js
> -module.exports = function(grunt) {
Well, it's two files that we need to bump. And I thought Grunt with Webpack is too much. They share a lot of the functionality.

2017-03-09 14:34 UTC, alshakero commented
@tomalec done. I tested again all the above tests and copied HTML spec runner to test minified files.

2017-03-09 15:30 UTC, tomalec requested changes
I would bump the version after merge, with single bump commit.
Other than that LGTM.

2017-03-09 15:30 UTC, tomalec commented on bower.json
> +  "version": "2.0.0",
have you already bumped the version

2017-03-09 16:02 UTC, tomalec approved these changes

2017-03-09 16:03 UTC, tomalec commented
LGTM, please merge, and bump major version

2017-03-09 16:18 UTC, merged